### ISSUE TITLE
Move the OperatorResourceList to the MemPool

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonevm/proxy-model.py#819]
# Impact

The strategy is to make the RPC worker as simple as possible and to make it able just get all the required resources and process the neon transaction compounded with the context stuff like resources, stage it were interrupted previous time, accounts it reads and writes and the like.

# What does it need for?

Further it'll be more easy to reschedule the transaction processing from the step it was interrupted previously

# TODO:

- [ ] Extract the OperatorResourceMng
- [ ] Prepare the use cases
- [ ] Cover the functionality with tests
